### ISSUE TITLE
Version 39.0.2171.95 m of Chrome not showing close button 

### ISSUE THREAD

**Issue by CarolusW** [ksylvest/jquery-lighter#6] opened 2015-01-03 16:13 UTC
Lighter works like charm on all platforms and browsers I've tested it on. Except when I'm using Version 39.0.2171.95 m of Chrome on w8.1 the popup/overlay it too big and expands off screen so the close buttons is inaccessible/does no show. 

Cheers 
Rickard

**Comment by ksylvest** [comment] 2015-01-14 02:29
@CarolusW Hey, sorry for the delay but would you mind re-verifying now? I added a few animation fixes and think this might be fixed in v1.2.4 but had a tough time reproducing as I don't run Windows 8.1.

**Comment by ksylvest** [comment] 2015-02-18 00:29
closing due to no response.

**Closed by ksylvest** 2015-02-18 00:29 UTC
